---
name: CI
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
  pull_request:
    paths-ignore:
      - '**/*.md'
  schedule:
    - cron: "30 3 * * 5"

jobs:
  lint:
    name: Lint Markdown
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v7

      - name: Lint Markdown files
        uses: DavidAnson/markdownlint-cli2-action@v23.2.0
        with:
          globs: '**/*.md'

  trigger-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger webhook to deploy Hugo website
        uses: distributhor/workflow-webhook@v3.0.8
        with:
          webhook_url: 'http://xserve.cc/hooks/deploy-hugo-site'
          webhook_secret: ${{ secrets.WEBHOOK_TOKEN }}
          verbose: true
