---
name: CI
on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "30 3 * * 5"

jobs:
  lint:
    name: Lint Markdown
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v7

      - name: Lint Markdown files
        uses: DavidAnson/markdownlint-cli2-action@v23.2.0
        with:
          globs: '**/*.md'

  deploy:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Trigger deployment to build Hugo website
        uses: distributhor/workflow-webhook@v3.0.8
        with:
          webhook_url: 'http://xserve.cc/hooks/deploy-hugo-website'
          webhook_secret: ${{ secrets.WEBHOOK_TOKEN }}
          webhook_type: 'json-extended'
